---
title: "Table S4"
subtitle: "Education Policy 4. Expansion of the category of students with LD among those eligible for special education, establish a diagnostic system, and form a consensus (topic 3, θ = .173)"
date: ""
tbl-colwidths: [20, 30, 50]
---

| **Education policies** | **Sub-policies** | **Practices** |
|------------------------|------------------|---------------|
| **4.1. Expansion of learning disability categories through expansion of related laws and diagnostic system** | **4.1.1. Revision of related laws and establishment of linkage and cooperation system to expand disability categories and establish a diagnostic system** | •	Engage in discussions to provide realistic and practical support and to reorganize laws and regulations other than school education regulations related to learning disabilities and challenges. <br> •	Connect related laws and regulations regarding educational support for eligible students such as the Lifelong Education Promotion Act, Act on Guaranteeing and Supporting Rights of Persons with Developmental Disabilities, local government ordinances, Ordinances on Career Education Promotion, and Ordinances on Promotion of Employment of People With Disabilities and Vocational Rehabilitation Support. <br> •	Promote public understanding and agreement on the definition and implementation plan for basic academic skills. |
|  | **4.1.2. Establishment of a cooperation system to expand disability categories and establish a diagnostic system** | •	Establish a cooperation system to support the development of students in and out of school through advice and consultations with learning help centers, special education support centers, above centers, special classes, and above classes in each city and region. <br> • Establish a specific philosophy and vision for cooperation. Only when there is a purpose and direction can a practical plan be derived. <br> •	Develop cooperation plans from the policy and program planning stage. <br>•	Establish standards for the specific division of roles and teaching methods for each teacher. <br> • Establish inter-departmental systems, such as education and welfare departments, special education systems, and career and vocational education systems. Break away from the current short-term, one-time program approach. <br> • Assign learning disability majors to departments related to basic academic abilities in each city and provincial office of education. Dispatch teachers specializing in special education or learning disabilities. <br> • Establish interconnectivity rather than a mutual comparison of the direction and intensity of support for students eligible for basic and special education. <br> • Establish reasonable measures with conflict management experts for handling cases where violence occurs due to students in special education or their parents. <br> • Suggest ways to connect and improve the education–welfare–medical system to support the education of infants and toddlers with disabilities. |
|  | **4.1.3. Diversification and advancement of diagnostic systems and programs** | • Diversify emotional/behavioral/social development programs in school, such as individual and small group counseling and treatment programs and academic dropout prevention programs. <br> • Establish clarity on policy measures and functions to increase the effectiveness of the multi-support team (support council). <br> • Establish a legal system that recognizes students’ educational needs as a spectrum and selects and provides appropriate support. <br> • Solve the problem of limited expert and assessment tools related to basic academic skills that are not teacher-friendly. <br> •	Institutionalize the participation of special education experts and follow-up measures when developing basic academic ability diagnostic tests. |
| **4.2. Securing of the role of special education within general education** | **4.2.1. Securing of special education teachers** | • Secure the supply and demand of special education teachers and develop a mid- to long-term expansion plan for the diversification of special schools (levels). <br> • Support the improvement of special education teachers’ capabilities and expertise in supporting emotional/behavioral/social development within schools and deploy additional experts when necessary. <br> • Expand the number of special teachers to ensure support for mild disabilities such as learning disabilities. |
|  | **4.2.2. Clarification of the roles of special education personnel within general education** | • Enhance the cooperation capacity of special education coordinators (visiting schools to provide advice similar to an inclusive education support group) and strengthen authority and accountability. <br> • Clarify the roles of special education support personnel (e.g., practitioners and instructors). <br> • Reorganize the curriculum and strengthen support measures for new teachers to include discussion and communication methods during teacher training and prospective teacher training.
