---
title: "Table S1"
subtitle: "Education Policy 1. Development of various programs to support and link basic academic skills (topic 5, θ = 0.214)"
date: ""
tbl-colwidths: [20, 30, 50]
---

| **Education policies** | **Sub-policies** | **Practices** |
|------------------------|------------------|---------------|
| **1.1.Establishment and advancement of multidimensional linkage system** | **1.1.1. Establishment and advancement of linkages between related organizations** | • Establish cooperation measures to strengthen connectivity between local schools, provincial and provincial offices of education, universities, and research institutes; and establish public/private/academic governance centered on local governments. <br> • Reduce the gap through education and childcare surveys. <br> • Prepare a linkage plan that considers regional characteristics and promote and cooperate actively at the Ministry of Education level. <br> • Establish and support the use of big data for student diagnosis and learning records at the provincial/provincial office of education level. |
|  | **1.1.2. Establishment and advancement of related laws and systems** | • Expand the scope of students eligible for special education. <br> • Organically link laws and regulations for related support after establishment of basic law. <br> • Redefine the concept of “lifelong education” for students eligible for special education. <br> • Initiate identifying relationships between students eligible for basic academic support under the Basic Skills Guarantee Act and students eligible for special education under the Act on Special Education for Persons with Disabilities.| 
|  | **1.1.3. Improvement of the conditions of existing special education for students with (learning) disabilities** | • Recommend counseling and intervention measures regardless of whether students are eligible for special education after deliberation by the Student Life Education Committee. <br> • Assign dedicated personnel to students with multiple disabilities. <br> • Develop and offer customized lifelong education programs considering the type and degree of disability. <br> • Establish and operate a customized distance education platform considering the type and degree of disability. |
| **1.2. Development of programs for students and parents related to basic academic support and connection** | **1.2.1. Support for basic academic skills and linkage of human and material resources** | • Establish a basic academic ability support center and a special education support center within the Office of Education (physically nearby) to facilitate mutual cooperation and communication. <br> • Clearly distinguish between roles that are linked to and independent from the basic academic ability support center. In the case of special education support centers, the spectrum of students eligible for special education supported is wide; thus, these centers should not be limited to the role of simply supporting basic academic ability. <br> • Actively support learning through resident or dispatched teachers. <br> • Assign and dispatch teachers in charge of basic academic ability to each school to address the lack of quality control with only the basic academic ability support manager. <br> • Cooperate to discover and support customized education programs. |
|  | **1.2.2. Development and dissemination of daily life and parenting programs related to basic academic ability support and connection** | • Provide support centered on daily life and life skills in addition to subjects such as reading and math. Existing test-centered learning adds difficulty to both parents and teachers. <br> • Prepare and operate parent education and complex support programs, including solutions to parents’ parenting stress and related family problems, psychological counseling, child education, parent capacity strengthening, and positive behavior support. <br> • Improve parental awareness of learning difficulties that are not revealed until the third grade of elementary school. |
|  | **1.2.3. Development and dissemination of programs for career paths, higher education, and lifelong education** | • Establish a local center for students with learning challenges to provide them support for career and transition education. <br> • Support business agreements to establish governance among private sectors (companies that employ students with disabilities), governments, and academic institutions and provide career and job experience. <br> • Expand field training opportunities for strengthening the employment support system for students with disabilities. |








