---
title: "Table S5"
subtitle: "Education Policy 5. Establishment and maintenance of policies, laws, and administrative systems to support students with LD (topic 4, θ = .169)"
date: ""
tbl-colwidths: [20, 30, 50]
---

| **Education policies** | **Sub-policies** | **Practices** |
|------------------------|------------------|---------------|
| **5.1. The establishment and maintenance of laws and systems** | **5.1.1. Clarification of the relationship and role between basic academic achievement support and special education and the establishment of a linked support system** | • Identify the relationship between students eligible for basic academic support under the Basic Academic Abilities Guarantee Act and students eligible for special education under the Special Education Act (whether or not they are included, etc.). <br> • establishing interconnectivity in decision-making regarding the direction and intensity of support for students eligible for basic academic achievement support and special education rather than becoming an issue for comparison 


. <br> • Assign learning disability majors to departments related to basic academic ability in each city/provincial office of education. Dispatch teachers specializing in special education or learning disabilities. <br> • Establish a legal system that recognizes students’ educational needs as a spectrum and selects and provides appropriate support. <br> • Establish a department (control tower) dedicated to basic academic achievement. <br> • Institutionalize the participation of special education experts and follow-up measures when developing diagnostic tests. |
|  | **5.1.2. Establishment and connection of laws and systems related to education support** | •	Connect relevant laws and regulations regarding educational support for target students. <br> •	Discuss the reorganization of laws other than school education guidelines related to learning disabilities and challenges. <br> •	Establish inter-departmental systems such as education and welfare departments, special education systems, and career and vocational education systems. |
|  **5.2. The establishment and maintenance of policies and administrative system** | **5.2.1. Establishment of comprehensive and practical support policies for the smooth operation of basic academic achievement support and special education** | •	Form and operate an expert-based policy advisory group. <br> • Pursue consistent application through review of overlapping, conflicting, and incomprehensible content in legal interpretation and legal advice. <br> • Secure the supply and demand of special education teachers and establish a mid- to long-term expansion plan for the diversification of special schools (levels). <br> •	Establish clarity on policy measures and functions to increase the effectiveness of the multi-tiered system of support team (support council). <br> • Develop cooperation plans from the policy and program planning stage. |
|  | **5.2.2. Clarification of the role of the Special Education Support Center and strengthening of the cooperation system with related organizations** | •	Establish a Basic Skills Support Center and a Special Education Support Center within the Office of Education Support to facilitate mutual cooperation and communication. <br> •	Clearly distinguish roles that are connected to and independent from the Basic Skills Support Center and Special Education Support Center. Given the wide spectrum of students eligible for special education, the roles of the centers should not be limited to providing support for students’ basic academic achievement. <br> • Establish a cooperation system to support the development of students in and out of school through advice and consultations with learning help centers, special education support centers, above centers, special classes, and above classes in each city and region. <br> • Enhance the cooperation capacity of special education coordinators and strengthen authority and accountability.
