---
title: "Table S2"
subtitle: "Education Policy 2. Planning for support of students with LD through cooperation and linkage (topic 6, θ = .199)"
date: ""
tbl-colwidths: [20, 30, 50]
---

| **Education policies** | **Sub-policies** | **Practices** |
|------------------------|------------------|---------------|
| **2.1. cooperation and connection between relevant professional organizations to support students with learning disabilities** | **2.1.1. Linkage with specialized organizations to support basic academic skills and behavioral problems of students with learning disabilities** | • Ensure a shared understanding of the needs of inclusive access to basic education for students with learning disabilities. <br> • Provide links to specialized medical institutions and vouchers for intensive support for serious behavioral problems of students with disabilities. <br> • Collaborate with local community organizations that directly deal with target students, private organizations such as Peach Market and the Citizens’ Association for Slow Learners, and research institutes to accumulate research materials and establish a circulation system to reflect policy research results. |
|  | **2.1.2. Support for students with learning disabilities by identifying and linking out-of-school youth education information** | • Set clear standards for information that is necessary and educationally effective for parents raising target students and strengthen information accessibility through consensus among expert groups within the Ministry of Education. <br> •	Connect with various organizations such as the Ministry of Education and Employment, the Ministry of Health and Welfare (cooperation with lifelong education institutions for individuals with developmental disabilities); the Ministry of Gender Equality and Family (out-of-school youth education); the Ministry of Culture, Sports and Tourism; and the Culture and Arts Education Center. <br> • Increase activities to protect human rights  for students with LD and human rights education to students eligible for special education. <br> • Prioritize understanding of out-of-school learning disabilities and learning challenges, and parents’ needs. | 
| **2.2. Diagnosis and education support by identifying key characteristics of students with learning disabilities and related disabilities** | **2.2.1. Identification of characteristics of students with learning disabilities and related disabilities and support for customized education** | • Establish a flexible and appropriate professional support system through sharing of student history and context (e.g., active professional intervention by providers on issues such as refusal to select special education recipients and selection of special education recipients with different types of disabilities). <br> • Designate relevant ministries to customize education for students with LD and learning challenges according to their individual characteristics  and providing necessary support for each life cycle. <br> • Public officials within the Ministry of Education should be aware of inter-departmental issues, change awareness through smooth communication and active sense of responsibility, and understand the people who support students with learning disabilities and learning challenges. <br> • Investigate and identify consultation and management roles in professional research institutions that provide common support for people with learning disabilities and learning challenges. |
|  | **2.2.2. Need for comprehensive information and systematic support based on the cognitive, psychological, and emotional characteristics of students with learning disabilities** | • Experiment with educational approaches according to the various cognitive, psychological, and emotional characteristics of students and develop a comprehensive manual of research results. <br> • Provide comprehensive information delivery and systematic support through inter-ministerial policy linkage for early detection of infants with or at risk for disabilities and early intervention to prevent secondary disabilities and promote development. <br> • Assign appropriate personnel by identifying the perspectives of various learners, related experiences, and expertise of persons in charge of inter-ministerial connection. |
|  | **2.2.3. Establishment of a multi-support team and connection system for diagnosis and intervention of students with learning disabilities** | • Form a multi-support team including special education teachers for clinical diagnosis and cooperation. <br> • Secure all professional personnel (e.g., therapists, social workers, and counselors) surrounding the student as members of the individualized education support team. <br> • Systemize close linkage with multi-tiered systems of support in the following order: (a) all-student intervention, (b) focus group intervention, and (c) diagnosis referral and intervention for students eligible for special education.
