---
title: "Table S3"
subtitle: "Education Policy 3. Strengthening the capabilities and functions of inclusive and special education classes, promoting educational models, and developing manuals (topic 2, θ = .178)"
date: ""
tbl-colwidths: [20, 30, 50]
---

| **Education policies** | **Sub-policies** | **Practices** |
|------------------------|------------------|---------------|
| **3.1. Strengthening of the capabilities and functions of inclusive and special education classes** | **3.1.1. Establishment of a linkage system necessary to support inclusive education for students with learning disabilities** | • Support the improvement of special education teachers’ capabilities and expertise in developing students’ emotional/behavioral/social skills within schools and deploying additional experts when necessary. <br> •	Establish a system for early primary screening, precise diagnosis of risk groups, customized support, and special education linkage before the third grade of elementary school. <br> •	Establish a legal system that can fill the gaps after initial support within the public education system. <br> • Enhance guidance and coordination of overall support for students by deploying and expanding professional staff specializing in special education to the School Inclusive Education Support Center of the Provincial and Provincial Office of Education. |
|  | **3.1.2. Sharing and operation of various programs to improve the quality of inclusive and special classes** | •	Promote unification of education policies, evaluate reality, avoid unnecessary double diagnosis and support, and establish a consistent support system through cooperation between the special education, teaching and learning, and basic academic support departments of the Ministry of Education and the Office of Education. <br> • Improve the quality of operation through expansion of inclusive classes, diverse application of special classes, and case sharing (privacy protection precautions). <br> • Cumulatively record performance evaluations within inclusive classes with individualized education programs. |
|  | **3.1.3. Establishment and expansion of a cooperative operating system for educational placement of students with learning disabilities in an inclusive education environment** | • Expand the number of special education teachers to ensure support for mild disabilities such as learning disabilities. <br> • Establish a clear operating system base and effective inclusive education plan for integration within general classes to improve the quality of inclusive education. <br> • Raise the awareness of school administrators about cooperation-based inclusive education and expanding training for administrators in all school levels and district offices (i.e., special education department and kindergarten, elementary, and secondary education office superintendents). <br> • Develop a plan for subject teachers with subject-specific expertise to have the philosophy and awareness of individualized education support. <br> • Expand various educational options using base special classes and assign additional teachers to base special classes. |
| **3.2. Development and promotion of educational model manuals** | **3.2.1. Development and evaluation of educational manuals to support students with learning disabilities** | • Prepare a manual through current case studies, such as the increase in demand for special classes, changes in the phenomenon of learning disabilities in young children according to changing times, and how care should be inclusive and individualized in the educational field. <br> •	Make mandatory volunteer and practice periods in special classes or schools during the practicum and student teaching of teacher training programs. <br> • Provide diagnostic evaluation scales and manuals that can be used in practice, as well as training to improve understanding and awareness related to test scores on various assessments. |
|  | **3.2.2. Development and promotion of educational models and platforms** | • Develop a manual for effective operation of the distance education platform (Open Learning Center). <br> • Inspect the educational environment of target students and providing infrastructure for distance education. <br> • Establish a learning platform through business agreements with institutions. <br> • Establish an artificial intelligence-based learning diagnostic system. <br> • Develop realistic educational materials using virtual and augmented reality at each level.

