---
title: "Table S6"
subtitle: "Education Policy 6. Strengthening the transition, career, vocational education, and lifelong education of students with LD (topic 1, θ = 0.067)"
date: ""
tbl-colwidths: [20, 30, 50]
---

| **Education policies** | **Sub-policies** | **Practices** |
|------------------------|------------------|---------------|
| **6.1. Support and diversification of transition, career, and vocational education through community connection for student independence and practical employment** | **6.1.1. Provision of transitional support according to the student life cycle** | • Provide not only support centered on subjects such as mathematics but also support centered on daily life and living skills. <br> • Develop and activate diverse and specialized career, vocational, and transition education programs linking school and local resources to have a positive impact on students’ independent lives, rights, self-esteem, sense of achievement, and success experiences. <br> • Establish a local center targeting learning challenges to provide support for career and transition education. <br> •	Support business agreements to establish governance between private sectors, governments, and academic institutions and expand field training opportunities for career and job experience. |
|  | **6.1.2. Strengthening of the employment support system for students with disabilities** | • Establish and operate support centers for students with disabilities in all universities. <br> • Establish and actively utilize universities’ support centers for individuals with disabilities. <br> • Establish a system to strengthen linkages with universities, community welfare centers, and lifelong education institutions to lead to students’ further advancement and employment after high school. <br> • Prepare an integrated plan that considers regional characteristics and ensure its active promotion and cooperation at the level of the Ministry of Education. |
| **6.2. Support and reinforcement of customized lifelong education that considers students’ individual characteristics** | **6.2.1. Support of customized lifelong education according to the individual characteristics of target students, such as students with learning disabilities, borderline intelligence, and learning challenges.** | • Redefine the concept of “lifelong education” for students eligible for special education. <br> • Develop and distribute customized lifelong education programs that consider the type and degree of disability. |
|  | **6.2.2. Development and operation of various programs connected to the community and securing of budget for programs** | • Develop various programs and secure budget for lifelong education for people with disabilities. <br> • Create a foundation for village education and a lifelong education ecosystem based on the community. <br> • Develop and operate lifelong education programs and provide information on learning materials through linkage with lifelong education institutions, colleges/universities, special education support institutions, youth schools, etc. in the community. <br> • Actively utilize the local government’s budget and various facilities in the local community for lifelong education led by the Office of Education. <br> • Strengthen publicity to improve the educational community and civic awareness of lifelong learning cities for people with disabilities.
